services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    container_name: mssql
    hostname: localhost
    ports:
      - '1430:1433'
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=1q2w3e4r!
    restart: always
    healthcheck:
      test:
        [
          'CMD-SHELL',
          "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 1q2w3e4r! -Q 'SELECT 1' || exit 1",
        ]
      interval: 10s
      retries: 10
      start_period: 10s

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'

  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - '2181:2181'

  kafka1:
    image: wurstmeister/kafka:latest
    container_name: kafka1
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092 # Kafka가 모든 인터페이스에서 포트 9092를 통해 청취하도록 설정
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092 # 외부에서 이 브로커에 접근할 수 있는 주소를 지정
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
